### ISSUE TITLE
this.off is not a function. (In 'this.off()', 'this.off' is undefined)

### ISSUE THREAD

**Issue by pankajpatel** [modulor-js/modulor#24]
https://github.com/modulor-js/modulor/blob/58d501026480c70f766bac6597efa13293cd2947/src/modulor.js#L321

On Safari and Safari UIWebView, this throws an error in case of continuous attach and detach.

when disconnectedCallback happens; if the modulor has not completely initialized, this .off stays undefined and throws error. My suggestion would be to make it `this.off && this.off()`

**Comment by nogizhopaboroda** [comment]
Good idea. Could you please make a pr on this? I don't have an environment where i could reproduce it

**Comment by pankajpatel** [comment]
Sure. I would also like to propose this same approach to following error on `this.trigger`

```
this.trigger is not a function. (In 'this.trigger("component-attached")', 'this.trigger' is undefined)
```

primary device throwing this error is Mobile Safari

**Comment by nogizhopaboroda** [comment]
https://github.com/modulor-js/modulor/pull/25 should fix this
